language: java
jdk:
- oraclejdk8
services:
- mysql
before_install:
- chmod +x mvnw
cache:
  directories:
  - "$HOME/.m2"
notifications:
  slack:
    secure: inK5pFWKR878Lso3CNYtdIlXuEzEJ/wMc6FDS2P8CD0N4jvbdEHUSjJNlvyxytYG66Sw2YL6yzOhBKP7LCjsH83VQ9vxzlA+6JjlO6a6p6Z7UTFMro02ppoAvNtJMP1i8HKt9pTEIMx2eea2auWtIbqR/RGhmD6ItnMHTymgDS7aaMztzDHBQ3lb7my0nVVP9jEaA6JeJ1Xlm19V1a2+RNDwkWmMEKTm4AzsdppB30+GwIsbYCw/wVZMo+hM7hhsGGfpvj2UanhOEdmVmX9MnH7z0QblLDcfzAaoXqdb+pscCuKNu+5YEiy5e2lCcIdsn7Jm7OC0UOCWZhm1TuhJA9YdaF87J0ZPRES1Jm7hw+z7Luekud+jEAIuHa1O3cswO5xb2AxFcchgNEUxeSxCyDTAQiWfOekrOJAhKw2SGx9yNgGknGR3txb09EuSrMW8A4Rzs46FRAyCJiSWo3ZL3pnl5si0dHe+lxfCTSDVBNAud107NAKyYKnNzd3ZSQoNoCkTimUoS195J2t6GSWaZsivtiY2jQbNu9K/A2Fp9neLPXFC7TGFjQXCatgzhA+PY2eVlB3FMdmB2FpSix5Mn4Qns/KjWwUQgoSExyFqQsNS+Arw34UHsgqbJZIKnTtnR4byli3UfXA5D9miBcDmU8ImrCY+oaR33zNpgpGyUvo=
        template:
          - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
          - "%{message} %{foo}"
