language: java
jdk:
- oraclejdk8
services:
- mysql
before_install:
- chmod +x mvnw
cache:
  directories:
  - "$HOME/.m2"

notifications:
  slack:
    secure: qQsPn9t9g0UCtShgJkaWpoX5WAoqbT77Y+yW8nNVx8JSg7f9+axoqFpdnbxxx676ERlAmqS4BkNzKPJgAvA86E+py2JQj0BzSX3JuIKHeBLc1whb2YDwlh97I+nU13OGGpAx5/SSCTE37U6dIlgiAF53RDKBMM0Rsuvkz7DdlfGrtYRYauUPrMwG8SXA2Oqg+QA0EYEKCMEOB48qmY3j9bIQ6YOR53h6s8GBYj71xKwDjgXuFaYP4PvubF4cKX+KLi1XOtZQcJQ6YMgGt7ea52ZVkKrh132IX5Y8isUeDwY4Nz7WQQJXyZhqOrctU9Ii3FF+TfwtMV/xLSmsC442hp0liTwKViHX/HGK1GOFO9XnCzGk6FkGKTG5aW5ozOzY5hQBDJwFT+eK/EPaukkhEnha1XrU24y/FCeTr+GFamzBNrhnvWnGCTCEFztY2IUJezQ2f9+7rLwi55n10M/Xa8yMeClpvet8zL5BfBbt4bl8bbtlJyzuO0X+HMx4BiN0n327suOxr9D2LmXkvxpx3XtmHD+Jm4gzZy3mmaERRE+ufa+thyAsGtsFffxWP++g/WRZD9C+SeTSATss929OYU5MPPvJoYHEjTmfZic1YH1T0iEBrNcEOG9fFj2X8Gll8dTKzNnHovmsFAaPc/TS1vJ0K0A+dWktzFuqfhaZssA=
