logging:
  path: logs
  pattern.console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %highlight(%-5level) %logger{10}.%M - %msg%n"
  pattern.file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger.%M - %msg%n"
  level.org.springframework.web: info



server.port: 8080
spring.mvc.view.suffix: .html

spring.datasource:
  url: ${JDBC_DATABASE_URL}
  username: ${JDBC_DATABASE_USERNAME}
  password: ${JDBC_DATABASE_PASSWORD}

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.datasource.initialize: true
spring.jpa:
  hibernate.ddl-auto: create-drop
  show-sql: false

spring.data.rest.base-path: /api



# optional in-memory h2 settings for testing if mysql db is unavailable
#
#spring.h2.console:
#  enabled: true
#  path: /h2
#
#spring.datasource:
#    url: jdbc:h2:mem:pindb
#    username: sa
#    password:
